// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_uFbkwbovKHFowL2zsCGkRpa01ZAFFU',
    appId: '1:955355413911:web:a97b495898647e4ad2d8d2',
    messagingSenderId: '955355413911',
    projectId: 'bill-43952',
    authDomain: 'bill-43952.firebaseapp.com',
    storageBucket: 'bill-43952.appspot.com',
    measurementId: 'G-FT46RDZ87E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsPpom_WqYGiJIVQKQ7pywuO5PL-taKYE',
    appId: '1:955355413911:android:443b63d55cb7d8a1d2d8d2',
    messagingSenderId: '955355413911',
    projectId: 'bill-43952',
    storageBucket: 'bill-43952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVGDeiPAWn9egT_vonItTGNGSfLC2Z_WQ',
    appId: '1:955355413911:ios:1507d6d93e35da5fd2d8d2',
    messagingSenderId: '955355413911',
    projectId: 'bill-43952',
    storageBucket: 'bill-43952.appspot.com',
    iosBundleId: 'com.example.factory1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVGDeiPAWn9egT_vonItTGNGSfLC2Z_WQ',
    appId: '1:955355413911:ios:1507d6d93e35da5fd2d8d2',
    messagingSenderId: '955355413911',
    projectId: 'bill-43952',
    storageBucket: 'bill-43952.appspot.com',
    iosBundleId: 'com.example.factory1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt_uFbkwbovKHFowL2zsCGkRpa01ZAFFU',
    appId: '1:955355413911:web:f3f18725936dc438d2d8d2',
    messagingSenderId: '955355413911',
    projectId: 'bill-43952',
    authDomain: 'bill-43952.firebaseapp.com',
    storageBucket: 'bill-43952.appspot.com',
    measurementId: 'G-H3350NFX55',
  );
}
